spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: client-service-route
            uri: http://localhost:8081
            predicates:
              - Path=/client/**
          - id: vehicle-service-route
            uri: http://localhost:8082
            predicates:
              - Path=/vehicle/**
          - id: maintenance-service-route
            uri: http://localhost:8083
            predicates:
              - Path=/maintenance/**